#!/bin/sh

# cheatsheet which shows sxhkd bindings in dmenu
cat $HOME/.config/sxhkd/sxhkdrc \
| awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' \
| column -t -s $'\t' | dmenu -i -l 20
