#!/bin/bash

# Script to display bar in dwm
while true
do
	VOL="$(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')"
    LOCALTIME=$(date +"%a %d %b, %H:%M")
	TEMP="$(($(cat /sys/class/thermal/thermal_zone0/temp) / 1000))°C"
    BAT="$(acpi -b | awk '{ print $4 }' | tr -d ',')"
    # xsetroot -name "$IP $BAT $VOL $TEMP $LOCALTIME $OTHERTIME"
    echo "$TEMP|$BAT|$VOL|$LOCALTIME"
	sleep 20s
done
