#!/bin/sh

# Script to reload an instance of polybar
if [ -z "$(pidof polybar)" ]; then
  notify-send "reloaded polybar" && launchpolybar &
else
  notify-send "reloaded polybar" && polybar-msg cmd restart
fi
