#!/bin/sh

# Simple script that uses maim to take a screenshot
output=$HOME/Pictures/Screenshots/"$(date +%Y-%b-%d-%H:%M).png"

menu() {
    echo "" | dmenu -p "How Long?" | xargs -I _ sleep "_"
}

case "$1" in
    "full") maim -u -q "$output" || exit;;
    "select") maim -s -u -q "$output" || exit ;;
    "fulltime") menu && maim -u -q "$output" || exit ;;
    "selecttime") menu && maim -s -u -q "$output" || exit ;;

esac

notify-send "Maim" "Screenshot Taken"
