#!/usr/bin/env bash

# search for directories
PROJECT=$(fd --hidden --absolute-path --type d --base-directory ~/projects/ | fzf +m --tmux bottom --layout reverse)

# just retrieve the project name, no need for absolute path
SHORT_NAME=$(basename "$PROJECT" | tr . _)

# if the operation is cancelled then abort the script
if [[ -z "$PROJECT" ]]; then
  exit 0
fi

# if the session to-be-created doesn't exist then create one in detached mode
if ! tmux has-session -t="$SHORT_NAME" 2>/dev/null; then
  tmux new-session -ds "$SHORT_NAME" -c "$PROJECT"
fi

# switch to the selected session
tmux switch-client -t "$SHORT_NAME"
